modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
modId="karelcraft"
version="1.0.0"
displayName="KarelCraft"
description='''Un mod sacré plein de poutines bénites.'''
authors="Karel Mahiet"

[[dependencies.karelcraft]]
modId="forge"
mandatory=true
versionRange="[46.0.14,)"
ordering="NONE"
side="BOTH"

[[dependencies.karelcraft]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
